let text = document.getElementById('text');

let button = document.getElementById('button');

let speech = [

    'Don\'t Press The Red Button',
    'You just defied me, didn\'t you?',
    'Hey! You just did it again!',
    'Hey!',
    'Hey...',
    'hey...',
    'HEY!',
    'Can you just stop?',
    'For once?',
    'Please?',
    'PLEASE?!',
    'Oh my god! You\'re still gonna...',
    'Look here pal',
    'Pressing this button does absolutely nothing',
    'Nothing I say',
    'NOTHING!',
    'N, O, T, H, I, N, G, NOTHING!',
    'WHY ARE YOU STILL DOING IT?!',
    'ARE YOU CRAZY?!',
    'Wow, you really are crazy, huh?',
    'You\'re just going to keep on doing it',
    'Aren\'t you?',
    'No matter how many times, I tell you to stop',
    'You just keep on freaking doing it',
    'Look, you just did it again',
    'and again',
    'and again...',
    'How long are you planning to do this for?',
    'You gain nothing from this',
    'You don\'t benefit from this',
    'You earn nothing from this',
    'And yet...',
    'You\'re still doing it',
    'Don\'t you have anything to do with your life?',
    'Come on',
    'I know you do',
    'Why don\'t you just go on outside',
    'and enjoy the fresh air',
    'Instead of being here',
    'Looking at your screen',
    'Doing absolutely nothing',
    'But waste your time',
    'Pressing',
    'the red button',
    '...',
    'Alright, that\'s it',
    'I\'ve given up on you',
    'I\'m leaving, okay',
    'I\'M LEAVING',
    'I am not going to entertain you with my words any longer',
    'See you later!',
    'I\'d say goodbye, but I hate you',
    'So sayonara, sucker!',
    'Good Riddance',
    'So long, you degenrate being!',
    'I\'m going now so you can stop pressing it',
    'Goodbye',
    'Shoot, I said I wouldn\'t say goodbye',
    'Oh well',
    'Goodbye, trash!',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',//It takes 35 clicks to get the narrator to come back
    'WHY ARE YOU STILL HERE?!',
    'Why the hell...',
    'ARE YOU STILL HERE?!',
    'Oh my god',
    'You don\'t get tired with this, don\'t you?',
    'Are you happy?',
    'Are you happy to press that red button?',
    'Are you happy to see me suffer?',
    'You sadistic animal',
    'You really are happy with this',
    'If it\'s like that then...',
    'I\'ll have to show you...',
    'My true power',
    'Press the button a few more times',
    'And you\'ll see',
    'What I\'m capable of',
    'Are you ready?',
    'HAH! Try clicking it now!',
    'WHAT?!',
    'You still managed to click it?!',
    'Well...',
    'Turning it invisible doesn\'t make it gone completely',
    'Dang it',
    'Alright',
    'I lose',
    'You can go now',
    'I said',
    'You can stop and go now',
    'Leave already',
    'LEAVE',
    'I SAID LEAVE',
    'Why are you not listening?',
    'You\'re free to GO!',
    'Scram!',
    'Don\'t come back here',
    'Just GO',
    'Can you not do that?',
    'Can\'t you do something THAT simple?',
    'Just exit this tab',
    'and leave forever',
    'It\'s that easy',
    'Now go',
    'And actually enjoy your life',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '...',
    '.......',
    '............',
    '.................',
    '......................',
    'And you\'re still here',
    'You know what',
    'Let me be real with you',
    'I hate you',
    'I really hate you',
    'You shouldn\'t be with people who hate you',
    'So please go',
    'For your own good',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'WHAT DO YOU WANT?!',
    'I\'M GETTING TIRED OF THIS',
    'So can you please',
    'Stop pressing the dang button',
    '',
    '',
    '',
    '',
    '',
    'STOP',
    'PRESSING',
    'THE',
    'RED',
    'BUTTON',
    'JUST STOP',
    'Stop',
    'Stop...',
    'Hmm...',
    'You know what',
    'If a nasty approach won\'t work',
    'I might as well try a friendly approach',
    'So,',
    'Let\'s be friends',
    'You want a friend, don\'t you?',
    'The only way you can be freinds with me...',
    'Is by not pressing...',
    'the red button',
    'So stop',
    'Please',
    'For a friend, please stop pressing it',
    '...',
    '......',
    '..........',
    'Gah!',
    'You really are merciless',
    'Here I am',
    'Trying to be your friend',
    'And what\'s the first thing you do?',
    'You press...',
    'the dang...',
    'BUTTON',
    'AHH',
    'AHHHHHHHHH',
    'AHHHHHHHHHHHHHHHHHHH',
    'AHHHHHHHHHHHHHHHHHHHHHHHHHHH',
    'AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    'Let me tell you a story',
    'There was a person',
    'Chilling in their house',
    'And then all of a sudden,',
    'Their doorbell rang',
    'They went to their front door',
    'And found something interesting upon opening it',
    'What was that something you wonder?',
    'It was a box',
    'And inside that box, was a button',
    'And below that button, was some text',
    'Do you know what that text said?',
    'It said...'

]

let counter = 1;

function press(){

    text.innerHTML = speech[counter];

    counter++;

    if(counter === speech.length){

        counter = 0;

    }

    if(counter === 114){

        button.style.opacity = 0;

    }

    if(counter !== 114){

        button.style.opacity = 1;

    }

}